server.port=8080
spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG
# MongoDB - FIXED KEY ✅
spring.mongodb.uri=${mongodb_uri}
spring.mongodb.database=swiftmove
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.socket-timeout=10000
spring.data.mongodb.connect-timeout=10000
spring.data.mongodb.server-selection-timeout=10000
spring.data.mongodb.heartbeat-socket-timeout=10000

# JWT
app.jwt.secret=${jwt_secret}
app.jwt.expiration=${jwt_expiration}

# CORS
app.cors.allowed-origins=${CORS_ORIGIN}

# Logging
logging.level.com.swiftmove=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR

# ORS
ors.api.key=${ors_api_key}

# App name
app.name=SwiftMove

# Mail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${mail_username}
spring.mail.password=${mail_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Razorpay
razorpay.key.id=${razorpay_id}
razorpay.key.secret=${razorpay_secret}

# KYC / File Upload
spring.data.mongodb.gridfs.bucket=kyc-documents
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB